### PR TITLE
Proposed fix and extra tests for DirectoryInfo static calls

### PR DESCRIPTION
**Pull request by NickJosevski**
Fix for https://github.com/kthompson/glob/issues/14

### CODE REVIEW

**Comment by kthompson** [comment]
It looks like the changes here have increased the time to test by quite a bit. It may be better to run the tests against the source folder even though it may change, also it would alleviate issues running under linux/osx.

**Comment by NickJosevski** [comment]
Yes, I notice that now, original tests ran <1 seconds on my machine, with my additions its approaching 7 seconds on my machine. 

My additions are really integration tests since they run against C:\Windows\Microsoft.NET and C:\ it will be quite a load. This won't work if you are running these tests on non Windows OS...

Maybe disable my additional tests for now.

**Comment by kthompson** [comment]
I went ahead and made a few tweaks to your tests that should hopefully preserve their intent but appveyor still seems to be a bit slow. I will take another look a bit later.

**Comment by NickJosevski** [comment]
Yes that was a good idea, lean on the on project solution to do those tests.

Build is still failing, with access denied to `C:\Documents and Settings` is that after your last change?

**Comment by kthompson** [comment]
Yea. I am guessing that the path on AppVeyor is different then via `dotnet test`

**Pull request merged**
